### ISSUE TITLE
Can't pull the docker image

### ISSUE THREAD

**Issue by floitsch** [heyhusen/archlinux-package-action#41]
When trying to use the action, I get the following error:
```
Pull down action image 'ghcr.io/hapakaien/archlinux-package-action:2'
  /usr/bin/docker pull ghcr.io/hapakaien/archlinux-package-action:2
  Error response from daemon: Head "https://ghcr.io/v2/hapakaien/archlinux-package-action/manifests/2": denied
  Warning: Docker pull failed with exit code 1, back off 6.712 seconds before retry.
```

**Comment by quexten** [comment]
@floitsch Did you find a solution to this in the meantime?

I'm having the same issue - it's breaking my release pipeline.

**Comment by quexten** [comment]
Ok, seems the maintainer decided to rename their GitHub account, which breaks all of the ~40 CI pipelines on GitHub using this. Even just renaming the reference in the GitHub CI wasn't enough because of caching. I decided to just drop this action, but if you want to use it, renaming to `ghcr.io/heyhusen/archlinux-package-action:2` will probably work.

**Comment by heyhusen** [comment]
I'm very sorry, guys. As @quexten said, I didn't expect this to cause so many problems. Now I know that my actions were irresponsible.

The latest version should fix this problem.

Once again, I am very sorry.

**Comment by quexten** [comment]
Ah, sorry didn't mean to come off as blaming you just to be clear. I think it's GitHub's fault to allow this. Imo, CI images should just remain, even if the owning account gets renamed or deleted.

Thanks for the update!

**Comment by floitsch** [comment]
Thanks for the fix. I upgraded our workflow.
Couldn't test it yet, but I think we will do another release next week.

**Comment by simeonschaub** [comment]
This is still not fully fixed, see the discussion in https://github.com/orgs/community/discussions/136632#discussioncomment-10433557. @heyhusen Could you update the `v2` branch to point to the updated repo name?

**Comment by heyhusen** [comment]
Oh, I forgot to update that. Is there anything else I need to fix? @simeonschaub

**Comment by simeonschaub** [comment]
Not AFAICT. Thanks for the fix!
